### PR TITLE
Capitalization fixes requested by Joe Lee.

### PR DESCRIPTION
**Pull request by FlipperPA**

### CODE REVIEW

**Comment by williln** [comment]
@FlipperPA Did I misunderstand his email? 

> “SIMPL” is really “Simpl”

I made that change here: https://github.com/djangocon/2018.djangocon.us/pull/144

**Comment by FlipperPA** [comment]
Wups, I think I got it backward. Confirming with Joe just so we can put this bed - PLEASE DO NOT MERGE! Thanks @williln

**Comment by FlipperPA** [comment]
Confirmed with Joe, @williln is correct! Nothing to see here... :)

**Comment by williln** [comment]
👍

**Pull request closed without merging**
