### PR TITLE
Add international travel news post

### PR DESCRIPTION
**Pull request by xirdneh**

### CODE REVIEW

**Comment by KatherineMichel** [comment]
Here are a few changes I suggest after running this locally, @xirdneh @williln @rebkin05 

Change the title and remove the line `# International Travel Information`. Otherwise, there are two titles and no teaser on the blog list page.

```
---
author: Josue Balandrano Coronel and Lacey Williams Henschel
category: General
date: 2018-07-23 08:00:00
layout: post
title: "International Travel Information"
---

Are you attending DjangoCon US 2018 in San Diego, California, but you are not from US and need some travel information? Here are some things to consider when planning your trip.
```

Put a space before the bullet list in Travel Paperwork. The formatting looks better with a space imo. 

```
These documents can be helpful when going through US Customs and Border Protection:

  - Printout of your invitation letter.
```

Under Valid Passport, change updated to up-to-date

Make U.S. either U.S. or US throughout post. It is written both ways.

Change mi to miles for clarity.

**Comment by xirdneh** [comment]
@rebkin05 Where can I get the DjangoCon 2018 image to place in one of the corners of the image?

**Comment by rebkin05** [comment]
@xirdneh Here you go! I grab logo-white.png. https://2018.djangocon.us/styleguide/#logo-files

**Comment by williln** [comment]
@xirdneh  I usually use `logo-white.png`, downloadable from the [styleguide](https://2018.djangocon.us/styleguide/#logo-files)

**Comment by KatherineMichel** [comment]
I think I created a new problem by suggesting a space between the bullet point list and the bullet point list within it. Which is preferable @mtrythall? With no space, the two lists look crowded together, but with a space, the line spacing in bullet point list 1 becomes bigger than the spacing of the other bullet points. I am tempted to put it back to no space even though looks a bit crowded.

**Comment by xirdneh** [comment]
@KatherineMichel everything should be ready to publish this. Thanks!

**Pull request merged**
