### PR TITLE
Around town blog post first draft

### PR DESCRIPTION
**Pull request by davidfischer**
After talking with Rebecca in slack, she proposed an "around town" blog post. I wrote the international travel guide getting around section and I adapted parts of it for this post. I think the goal is to just name a few things and point out some ways to get there. I think people can mostly do their own research on Google Maps, Yelp, Trip Advisor and other services.

If we don't need or want this kind of post, I'd be fine closing it without merging. However, if it's useful, here's a first draft at least. I'd be happy to revise it as well.

### CODE REVIEW

**Comment by rebkin05** [comment]
@davidfischer It looks great, thank you! 🎉 Could you cap the "C" in DjangoCon on line 10 and then add a link to the trolley's website? I'm thinking of publishing this later this week or early next week.

**Comment by davidfischer** [comment]
I made those two changes.

**Comment by jefftriplett** [comment]
Scheduled to go out 9/29 🎉

**Comment by davidfischer** [comment]
> Scheduled to go out 9/27

I'll update the date on the post.

**Pull request merged**
