### PR TITLE
Updates to the Venue page

### PR DESCRIPTION
**Pull request by davidfischer**
- Add places around San Diego
- Added `TODO`s to things on the venue page that require additional updating
- Updated map links to the venue

The Marriott is a great venue but a lot of the places nearby are chain restaurants so I added some places a bit further away as well.

Hopefully @treyhunner approves of my places around San Diego.

### CODE REVIEW

**Comment by davidfischer** [comment]
The errors on Travis don't seem to be anything I introduced.

**Comment by KatherineMichel** [comment]
LGTM! Thank you for your help @davidfischer. Don't worry about Travis CI. I think the errors are broken paths that will be fixed/removed. Happy to have updates from you, @treyhunner, anyone familiar with area if you think of something else.

**Comment by jefftriplett** [comment]
@davidfischer thank you for these. I'll fix Travis over lunch since it's grumpy from our mockups.

**Comment by davidfischer** [comment]
I simply chose the same number of places as were there last year. If you want more places, I could choose some more. At the same time a better place for that might be a blog post or small handout or something.

**Comment by KatherineMichel** [comment]
I think last year we limited it because it began to be too long. https://github.com/djangocon/2017.djangocon.us/pull/147

There might have been some talk of randomizing it, but not sure that there was a straight forward way to do it.

**Comment by jefftriplett** [comment]
I wouldn't double the number, but if there are an even-numbered more that you'd like people to know about, I'm sure they'd appreciate it.

**Pull request merged**
